import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { bindings } from './bindings.mjs';

const root = new URL('../../', import.meta.url);
const catalog = JSON.parse(await readFile(new URL('docs/api-index.json', root), 'utf8'));
const names = new Set(catalog.components.map(component => component.name));
for (const name of Object.keys(bindings)) if (!names.has(name)) throw new Error(`Binding has no Kit authority: ${name}`);
for (const component of catalog.components) {
  const signatures = ['construct', 'options', 'commands', 'queries'].flatMap(key => component[key] ?? []);
  for (const methods of Object.values(bindings[component.name]?.nativeMethods ?? {})) {
    for (const name of Object.keys(methods)) {
      if (!signatures.some(signature => signature.startsWith(`${name}(`))) throw new Error(`Native binding has no Rust method authority: ${component.name}.${name}`);
    }
  }
}
const components = catalog.components.map(component => ({
  name: component.name,
  source: component.source,
  path: component.path,
  binding: bindings[component.name] ?? { status: 'unbound', reason: 'Native adapter and behavioral tests not implemented' },
  rustSignatures: Object.fromEntries(['construct', 'options', 'commands', 'queries', 'slots'].map(key => [key, component[key] ?? []])),
}));
const json = JSON.stringify({ schema: 1, authority: 'docs/api-index.json', components }, null, 2) + '\n';
// These types describe coverage and retain source handles; unbound components are
// not counterfeit constructors. Runtime APIs are declared separately in sdk.d.ts.
const declarations = '// Generated by catalog.mjs. Coverage metadata, not native constructors.\n' +
  'export interface KitBindingCatalog {\n' + components.map(c =>
    `  readonly ${JSON.stringify(c.name)}: { readonly source: ${JSON.stringify(c.source)}; readonly status: ${JSON.stringify(c.binding.status)} };`
  ).join('\n') + '\n}\nexport type KitComponentName = keyof KitBindingCatalog;\n';
for (const [name, contents] of [['binding-coverage.json', json], ['catalog.d.ts', declarations]]) {
  const path = new URL(name, import.meta.url);
  if (process.argv.includes('--check')) {
    if (await readFile(path, 'utf8') !== contents) throw new Error(`Stale ${fileURLToPath(path)}; run node tools/js-runtime/catalog.mjs`);
  } else { await writeFile(path, contents); }
}
console.log(`Kit binding coverage: ${components.filter(c => c.binding.status !== 'unbound').length}/${components.length} components partially bound; remaining adapters explicitly unavailable`);
