// Generated by navigation_extra/fixture/generate.mjs; do not edit.
import type { KitNode, SlotNode } from './kit-sdk.js';
import type { BuiltinIconDescriptor } from './kit-icon-sdk.js';
export interface LayoutExtraFactories {
  AspectRatio(id: string, props: { ratio: number; fit?: "width" | "height" }, events?: Record<string, never>, slots?: { "content"?: SlotNode[] }): KitNode;
  Container(id: string, props?: { width?: "full" | "readable" | "dialog" | "custom"; customWidth?: number; padding?: "xxs" | "xs" | "sm" | "md" | "lg" | "xl" | "xxl" }, events?: Record<string, never>, slots?: { "content"?: SlotNode[] }): KitNode;
  Grid(id: string, props?: { columns?: number; columnsAt?: Array<{ breakpoint: "small" | "medium" | "large" | "extraLarge"; columns: number }>; gap?: "xxs" | "xs" | "sm" | "md" | "lg" | "xl" | "xxl"; items?: Array<{ id: string; span?: number; spanAt?: Array<{ breakpoint: "small" | "medium" | "large" | "extraLarge"; span: number }> }> }, events?: Record<string, never>, slots?: Record<string, SlotNode[]>): KitNode;
  Responsive(id: string, props: { threshold: number; fill?: boolean }, events?: Record<string, never>, slots?: { "unmeasured"?: SlotNode[]; "narrow"?: SlotNode[]; "wide"?: SlotNode[] }): KitNode;
  ScrollFade(id: string, props?: { top?: boolean; bottom?: boolean; left?: boolean; right?: boolean; band?: number; fitHeight?: boolean }, events?: Record<string, never>, slots?: { "content"?: SlotNode[] }): KitNode;
  ScrollEdgeEffect(id: string, props?: { top?: boolean; bottom?: boolean; left?: boolean; right?: boolean; band?: number; blur?: number; kind?: "soft" | "hard" }, events?: Record<string, never>, slots?: { "content"?: SlotNode[] }): KitNode;
  SplitTree(id: string, props: { disabled?: boolean; records: Array<{ id: string; parent?: string; ratio?: number; minWidth?: number; minHeight?: number; rail?: number; collapsed?: boolean; kind: "pane" | "horizontal" | "vertical" }> }, events?: { change?(value: { kind: "ratio"; split: string; ratio: number } | { kind: "collapsed"; split: string; side: "start" | "end"; pane: string }): void }, slots?: Record<string, SlotNode[]>): KitNode;
  DockTree(id: string, props: { disabled?: boolean; records: Array<{ id: string; parent?: string; ratio?: number; minWidth?: number; minHeight?: number; rail?: number; collapsed?: boolean; kind: "stack"; panels?: Array<string>; active?: string } | { id: string; parent?: string; ratio?: number; minWidth?: number; minHeight?: number; rail?: number; collapsed?: boolean; kind: "horizontal" | "vertical" }>; floating?: Array<{ stack: { id: string; parent?: string; ratio?: number; minWidth?: number; minHeight?: number; rail?: number; collapsed?: boolean; kind: "stack"; panels?: Array<string>; active?: string } | { id: string; parent?: string; ratio?: number; minWidth?: number; minHeight?: number; rail?: number; collapsed?: boolean; kind: "horizontal" | "vertical" }; bounds: { x: number; y: number; width: number; height: number } }>; panels?: Array<{ id: string; title: string; badge?: string; unavailable?: string; icon?: BuiltinIconDescriptor }> }, events?: { event?(value: { kind: "floatingRaised"; stack: string } | { kind: "floatingCancelled"; stack: string } | { kind: "floatingChanged"; stack: string; bounds: { x: number; y: number; width: number; height: number }; finished: boolean } | { kind: "panelSelected"; stack: string; panel: string } | { kind: "panelMoved"; panel: string; toStack: string; before: string | null } | { kind: "panelSplit"; panel: string; targetStack: string; placement: "left" | "right" | "top" | "bottom" } | { kind: "splitResized"; split: string; ratio: number } | { kind: "stackCollapsed"; stack: string; collapsed: boolean }): void }, slots?: Record<string, SlotNode[]>): KitNode;
  Dock(id: string, props?: { disabled?: boolean; panels?: Array<{ id: string; title: string; badge?: string; unavailable?: string; icon?: BuiltinIconDescriptor; region: "left" | "centre" | "right" | "bottom" }>; regions?: Array<{ id: "left" | "centre" | "right" | "bottom"; active?: string; collapsed?: boolean; share?: number; minSize?: number }> }, events?: { event?(value: { kind: "panelSelected"; region: "left" | "centre" | "right" | "bottom"; panel: string } | { kind: "panelMoved"; panel: string; toRegion: "left" | "centre" | "right" | "bottom"; before: string | null } | { kind: "regionCollapsed"; region: "left" | "centre" | "right" | "bottom"; collapsed: boolean } | { kind: "regionResized"; region: "left" | "centre" | "right" | "bottom"; ratio: number }): void }, slots?: Record<string, SlotNode[]>): KitNode;
  Toolbar(id: string, props?: { size?: "xs" | "sm" | "md" | "lg"; label?: string; groups?: Array<{ id: string; spacer?: boolean }>; items?: Array<{ id: string; label: string; group: string; disabled?: boolean; shortcut?: string; icon?: BuiltinIconDescriptor }>; overflow?: boolean; overflowAfter?: number }, events?: { overflowSelect?(value: string): void }, slots?: Record<string, SlotNode[]>): KitNode;
  DesktopTitlebar(id: string, props: { title: string; subtitle?: string; buttons?: { left?: Array<"minimize" | "maximize" | "close">; right?: Array<"minimize" | "maximize" | "close"> }; controls?: { fullscreen: boolean; maximize: boolean; minimize: boolean; windowMenu: boolean } }, events?: { event?(value: "minimize" | "toggleMaximize" | "close"): void }, slots?: { "left"?: SlotNode[]; "right"?: SlotNode[] }): KitNode;
  StatusBar(id: string, props?: { label?: string; items?: Array<{ id: string; label: string; group?: "start" | "centre" | "end"; kind?: "text" | "state" | "progress" | "action" | "element"; tone?: "neutral" | "accent" | "success" | "warning" | "danger" | "info"; disabled?: boolean; stale?: boolean; stateName?: string; fraction?: number; count?: { done: number; total: number }; icon?: BuiltinIconDescriptor }> }, events?: { click?(value: string): void }, slots?: Record<string, SlotNode[]>): KitNode;
}
export interface LayoutExtraMethods {
  AspectRatio: {
    invoke: {
    };
    query: {
      ratio: { args: Record<string, never>; result: number };
    };
  };
  Toolbar: {
    invoke: {
    };
    query: {
      item_count: { args: Record<string, never>; result: number };
    };
  };
}
