// Generated by navigation_extra/fixture/generate.mjs; do not edit.
import type { KitNode, SlotNode } from './kit-sdk.js';
import type { BuiltinIconDescriptor } from './kit-icon-sdk.js';
export interface NavigationExtraFactories {
  AnchorList(id: string, props?: { disabled?: boolean; size?: "xs" | "sm" | "md" | "lg"; anchors?: Array<{ id: string; label: string; disabled?: boolean }>; active?: string; overflow?: boolean; overflowAfter?: number }, events?: { navigate?(value: string): void }, slots?: Record<string, never>): KitNode;
  Breadcrumb(id: string, props?: { crumbs?: Array<{ id: string; label: string }>; maxVisible?: number }, events?: { select?(value: string): void; reveal?(value: Array<string>): void }, slots?: Record<string, never>): KitNode;
  Collapsible(id: string, props: { disabled?: boolean; size?: "xs" | "sm" | "md" | "lg"; title: string; description?: string; open?: boolean }, events?: { toggle?(value: boolean): void }, slots?: { "body"?: SlotNode[] }): KitNode;
  Carousel(id: string, props?: { size?: "xs" | "sm" | "md" | "lg"; items?: Array<{ id: string; label: string }>; active?: string; phase?: "idle" | "queued" | "blocked" | "loading" | "refreshing" | "ready" | "empty" | "unavailable" | "error" | "cancelled"; reason?: string; stale?: boolean; looped?: boolean }, events?: { event?(value: { kind: "selected"; id: string } | { kind: "previous" } | { kind: "next" }): void }, slots?: Record<string, SlotNode[]>): KitNode;
  NavStack(id: string, props: { entries: Array<{ id: string }>; cursor: number; label: string }, events?: Record<string, never>, slots?: Record<string, SlotNode[]>): KitNode;
  Sidebar(id: string, props?: { disabled?: boolean; size?: "xs" | "sm" | "md" | "lg"; sections?: Array<{ id: string; title?: string }>; items?: Array<{ id: string; label: string; section: string; within?: string; disabled?: boolean; badge?: string; icon?: BuiltinIconDescriptor }>; active?: string; collapsed?: boolean }, events?: { select?(value: string): void }, slots?: { "header"?: SlotNode[]; "footer"?: SlotNode[] }): KitNode;
  UndoHistory(id: string, props: { disabled?: boolean; label: string; entries?: Array<{ id: string; label: string; description?: string; time?: string; source?: string; unavailable?: string }>; current?: string }, events?: { jump?(value: string): void }, slots?: Record<string, never>): KitNode;
  Wizard(id: string, props?: { disabled?: boolean; size?: "xs" | "sm" | "md" | "lg"; steps?: Array<{ id: string; title: string; description?: string; status?: "upcoming" | "current" | "complete" | "blocked" | "failed"; reason?: string; reachable?: boolean }>; layout?: "horizontal" | "vertical"; backTo?: string; finish?: boolean; canAdvance?: boolean; backLabel?: string; nextLabel?: string; finishLabel?: string }, events?: { navigate?(value: { kind: "step"; id: string } | { kind: "back" } | { kind: "next" } | { kind: "finish" }): void }, slots?: { "body"?: SlotNode[] }): KitNode;
}
export interface NavigationExtraMethods {
}
