// Generated by content/fixture/generate-types.mjs. Native IO is unsupported.
import type { KitNode, KitSlots, SlotNode } from './kit-sdk.js';
export interface MediaFactories {
  AudioWaveform(id: string, props?: { "peaks"?: Array<number>; "playhead"?: number; "state"?: "loading" | "empty" | "unavailable" | "error" | "ready"; "reason"?: string }, events?: Record<string, never>, slots?: { "empty"?: SlotNode[] }): KitNode<'AudioWaveform'>;
  AudioPlayer(id: string, props?: { "disabled"?: boolean; "title"?: string; "elapsed"?: string; "remaining"?: string; "stepSeconds"?: number; "speeds"?: Array<number>; "subtitle"?: string; "peaks"?: Array<number> }, events?: Record<string, never>, slots?: Record<string, never>): KitNode<'AudioPlayer'>;
  VideoPlayer(id: string, props?: { "disabled"?: boolean; "title"?: string; "elapsed"?: string; "remaining"?: string; "stepSeconds"?: number; "speeds"?: Array<number>; "ratio"?: number; "posterResource"?: { "key": string } }, events?: Record<string, never>, slots?: { "poster"?: SlotNode[] }): KitNode<'VideoPlayer'>;
  ModelViewer(id: string, props?: { "disabled"?: boolean; "title"?: string; "document"?: string; "state"?: "empty" | "loading"; "shading"?: "flat" | "wireframe"; "yaw"?: number; "pitch"?: number; "height"?: number }, events?: { event?(payload: { "kind": "orbitChanged" | "shadingChanged"; "yaw"?: number; "pitch"?: number; "shading"?: "flat" | "wireframe" }): void }, slots?: Record<string, never>): KitNode<'ModelViewer'>;
}
export interface MediaMethodContracts {

}
declare module './kit-sdk.js' { interface KitFactories extends MediaFactories {} }
