// Generated by navigation_extra/fixture/generate.mjs; do not edit.
import type { KitNode, SlotNode } from './kit-sdk.js';
import type { BuiltinIconDescriptor } from './kit-icon-sdk.js';
export type DateAdapterData = { today?: number | null; weekdays: Array<string>; months: Array<{ month: number; label: string; weeks: Array<Array<{ day?: number | null; adjacent?: boolean }>> }>; days: Array<{ day: number; month: number; label: string; formatted: string; aliases?: Array<string>; blocked?: string | null }>; parseError: string; unknownDay: string; completeRange?: boolean; clock: { hourMin: number; hourMax: number; minuteMax: number; secondMax: number; meridiem?: Array<string> | null; hours: Array<string>; minutes: Array<string>; seconds: Array<string>; separator: string; meridiemSeparator: string } };
export interface DatetimeFactories {
  Calendar(id: string, props: { adapter: DateAdapterData; selected?: Array<number>; multi?: boolean; month?: number; range?: { start: number; end?: number | null } | null; disabled?: boolean; marks?: Array<{ day: number; label: string; tone?: "neutral" | "accent" | "success" | "warning" | "danger" | "info" }> }, events?: { pick?(value: number): void; monthShown?(value: number): void; hover?(value: number | null): void }, slots?: { "empty"?: SlotNode[] }): KitNode;
  DateInput(id: string, props: { adapter: DateAdapterData; value?: number | null; required?: boolean; invalid?: boolean; disabled?: boolean; size?: "xs" | "sm" | "md" | "lg" }, events?: { change?(value: number): void; unparsable?(value: { text: string; message: string }): void; open?(value: null): void; close?(value: null): void; submit?(value: null): void }, slots?: Record<string, never>): KitNode;
  RangePicker(id: string, props: { adapter: DateAdapterData; range?: { start: number; end?: number | null } | null; disabled?: boolean; invalid?: boolean; marks?: Array<{ day: number; label: string; tone?: "neutral" | "accent" | "success" | "warning" | "danger" | "info" }> }, events?: { startPick?(value: number): void; endPick?(value: number): void }, slots?: Record<string, never>): KitNode;
  TimeInput(id: string, props: { adapter: DateAdapterData; value?: { hour: number; minute: number; second?: number | null; meridiem?: 0 | 1 | null }; seconds?: boolean; disabled?: boolean; invalid?: boolean; size?: "xs" | "sm" | "md" | "lg" }, events?: { change?(value: { hour: number; minute: number; second?: number | null; meridiem?: 0 | 1 | null }): void }, slots?: Record<string, never>): KitNode;
}
export interface DatetimeMethods {
  Calendar: {
    invoke: {
      set_disabled: { args: { disabled: boolean }; result: null };
      set_overlay: { args: { marks: Array<{ day: number; label: string; tone?: "neutral" | "accent" | "success" | "warning" | "danger" | "info" }> }; result: null };
      reset_navigation: { args: Record<string, never>; result: null };
      set_selection: { args: { days: Array<number> }; result: null };
      set_multi: { args: { multi: boolean }; result: null };
      set_range: { args: { range: { start: number; end?: number | null } | null }; result: null };
      set_hovered_day: { args: { day: number | null }; result: null };
      shift: { args: { delta: number }; result: null };
      show_month: { args: { month: number }; result: null };
    };
    query: {
      is_disabled: { args: Record<string, never>; result: boolean };
      adapter_snapshot: { args: Record<string, never>; result: { today: number | null; weekdays: Array<string>; clock: { hourMin: number; hourMax: number; minuteMax: number; secondMax: number; meridiem: Array<string> | null } } };
      selection: { args: Record<string, never>; result: Array<number> };
      cursor: { args: Record<string, never>; result: number | null };
      hovered_day: { args: Record<string, never>; result: number | null };
      shown_month: { args: Record<string, never>; result: number | null };
    };
  };
  DateInput: {
    invoke: {
      set_disabled: { args: { disabled: boolean }; result: null };
      set_invalid: { args: { invalid: boolean }; result: null };
      set_control_size: { args: { size: "xs" | "sm" | "md" | "lg" }; result: null };
      set_value: { args: { value: number | null }; result: null };
      set_required: { args: { required: boolean }; result: null };
      open: { args: Record<string, never>; result: null };
      close: { args: Record<string, never>; result: null };
      toggle: { args: Record<string, never>; result: null };
    };
    query: {
      is_disabled: { args: Record<string, never>; result: boolean };
      field_snapshot: { args: Record<string, never>; result: { value: string; cursor: number; selection: { start: number; end: number }; disabled: boolean } };
      calendar_snapshot: { args: Record<string, never>; result: { selection: Array<number>; cursor: number | null; hoveredDay: number | null; shownMonth: number | null; disabled: boolean } };
      current: { args: Record<string, never>; result: number | null };
      parsed_day: { args: Record<string, never>; result: number | null };
      message: { args: Record<string, never>; result: string | null };
      is_open: { args: Record<string, never>; result: boolean };
      shown_text: { args: Record<string, never>; result: string };
      is_invalid: { args: Record<string, never>; result: boolean };
    };
  };
  RangePicker: {
    invoke: {
      set_disabled: { args: { disabled: boolean }; result: null };
      set_invalid: { args: { invalid: boolean }; result: null };
      set_overlay: { args: { marks: Array<{ day: number; label: string; tone?: "neutral" | "accent" | "success" | "warning" | "danger" | "info" }> }; result: null };
      set_range: { args: { range: { start: number; end?: number | null } | null }; result: null };
    };
    query: {
      is_disabled: { args: Record<string, never>; result: boolean };
      calendar_snapshot: { args: Record<string, never>; result: { selection: Array<number>; cursor: number | null; hoveredDay: number | null; shownMonth: number | null; disabled: boolean } };
      current_range: { args: Record<string, never>; result: { start: number; end?: number | null } | null };
      state: { args: Record<string, never>; result: "unset" | "incomplete" | "complete" | "end before start" };
      blocked: { args: Record<string, never>; result: { kind: "notApplicable" } | { kind: "unchecked" } | { kind: "clear" } | { kind: "blocked"; days: Array<{ day: number; reason: string }> } };
    };
  };
  TimeInput: {
    invoke: {
      set_disabled: { args: { disabled: boolean }; result: null };
      set_invalid: { args: { invalid: boolean }; result: null };
      set_control_size: { args: { size: "xs" | "sm" | "md" | "lg" }; result: null };
      set_value: { args: { value: { hour: number; minute: number; second?: number | null; meridiem?: 0 | 1 | null } }; result: null };
      set_seconds: { args: { seconds: boolean }; result: null };
    };
    query: {
      is_disabled: { args: Record<string, never>; result: boolean };
      current: { args: Record<string, never>; result: { hour: number; minute: number; second?: number | null; meridiem?: 0 | 1 | null } };
      active_segment: { args: Record<string, never>; result: "hour" | "minute" | "second" | "meridiem" };
      clock: { args: Record<string, never>; result: { hourMin: number; hourMax: number; minuteMax: number; secondMax: number; meridiem: Array<string> | null } };
    };
  };
}
