// Reproducible wire artifacts; the explicit family schemas, not api-index,
// define the implemented native surface. Run with --write to regenerate.
import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { pathToFileURL } from 'node:url';
import { iconSchema } from '../../../../../js-runtime/kit-icon-schema.mjs';
import * as navigation from '../../../../../js-runtime/kit-navigation_extra-schema.mjs';
import * as layout from '../../../../../js-runtime/kit-layout_extra-schema.mjs';
import * as datetime from '../../../../../js-runtime/kit-datetime-schema.mjs';
export const families = { navigation_extra: navigation, layout_extra: layout, datetime };
const names = { navigation_extra: 'NavigationExtra', layout_extra: 'LayoutExtra', datetime: 'Datetime' };
function type(schema, expand = false) {
  if (schema === iconSchema) return 'BuiltinIconDescriptor';
  if (!expand && schema === datetime.adapterSchema) return 'DateAdapterData';
  let result;
  if (schema.oneOf) result = schema.oneOf.map(v => type(v)).join(' | ');
  else if (schema.enum) result = schema.enum.map(v => JSON.stringify(v)).join(' | ');
  else if (schema.type === 'array') result = `Array<${type(schema.items)}>`;
  else if (schema.type === 'object') result = Object.keys(schema.fields).length ? `{ ${Object.entries(schema.fields).map(([key, value]) => `${key}${schema.required.includes(key) ? '' : '?'}: ${type(value)}`).join('; ')} }` : 'Record<string, never>';
  else result = schema.type;
  return schema.nullable ? `${result} | null` : result;
}
export function declarations(family) {
  const { familySchemas: schemas, familyMethods: methods } = families[family];
  const lines = ["// Generated by navigation_extra/fixture/generate.mjs; do not edit.", "import type { KitNode, SlotNode } from './kit-sdk.js';", "import type { BuiltinIconDescriptor } from './kit-icon-sdk.js';"];
  if (family === 'datetime') lines.push(`export type DateAdapterData = ${type(datetime.adapterSchema, true)};`);
  lines.push(`export interface ${names[family]}Factories {`);
  for (const [component, schema] of Object.entries(schemas)) {
    const events = Object.entries(schema.events).map(([event, schema]) => `${event}?(value: ${type(schema)}): void`).join('; ');
    const slots = schema.slotIds ? 'Record<string, SlotNode[]>' : schema.slots?.length ? `{ ${schema.slots.map(slot => `${JSON.stringify(slot)}?: SlotNode[]`).join('; ')} }` : 'Record<string, never>';
    lines.push(`  ${component}(id: string, props${schema.props.required.length ? '' : '?'}: ${type(schema.props)}, events?: ${events ? `{ ${events} }` : 'Record<string, never>'}, slots?: ${slots}): KitNode;`);
  }
  lines.push('}', `export interface ${names[family]}Methods {`);
  for (const [component, modes] of Object.entries(methods)) {
    lines.push(`  ${component}: {`);
    for (const [mode, methods] of Object.entries(modes)) {
      lines.push(`    ${mode}: {`);
      for (const [name, schema] of Object.entries(methods)) lines.push(`      ${name}: { args: ${type(schema.args)}; result: ${type(schema.result)} };`);
      lines.push('    };');
    }
    lines.push('  };');
  }
  return [...lines, '}', ''].join('\n');
}
export async function artifacts(write = false) {
  for (const [family, schemas] of Object.entries(families)) {
    const fixture = new URL(`../../${family}/fixture/`, import.meta.url);
    await mkdir(fixture, { recursive: true });
    for (const [name, content] of [['schemas.json', JSON.stringify(schemas.familySchemas, null, 2) + '\n'], ['methods.json', JSON.stringify(schemas.familyMethods, null, 2) + '\n']]) {
      const path = new URL(name, fixture);
      if (write) await writeFile(path, content);
      else if (await readFile(path, 'utf8') !== content) throw Error(`${family}/${name} stale`);
    }
    const path = new URL(`../../../../../js-runtime/kit-${family}-sdk.d.ts`, import.meta.url);
    if (write) await writeFile(path, declarations(family));
    else if (await readFile(path, 'utf8') !== declarations(family)) throw Error(`${family} SDK stale`);
  }
}
if (process.argv[1] && pathToFileURL(process.argv[1]).href === import.meta.url) await artifacts(process.argv.includes('--write'));
