// Reproducible family declarations; invoked by focused JS tests with --check.
import { readFileSync, writeFileSync } from 'node:fs';
const root = new URL('../../../../../js-runtime/', import.meta.url);
function type(schema) {
  const result = schema.enum ? schema.enum.map(value => JSON.stringify(value)).join(' | ')
    : schema.type === 'array' ? `Array<${type(schema.items)}>`
      : schema.type === 'object' ? Object.keys(schema.fields).length
        ? `{ ${Object.entries(schema.fields).map(([key, value]) => `${JSON.stringify(key)}${schema.required.includes(key) ? '' : '?'}: ${type(value)}`).join('; ')} }`
        : 'Record<string, never>' : schema.type;
  return schema.nullable ? `${result} | null` : result;
}
for (const family of ['content', 'media']) {
  const { familySchemas, familyMethods } = await import(new URL(`kit-${family}-schema.mjs`, root));
  const name = family[0].toUpperCase() + family.slice(1);
  const factories = Object.entries(familySchemas).map(([component, schema]) => {
    const events = Object.keys(schema.events).length ? `{ ${Object.entries(schema.events).map(([name, schema]) => `${name}?(payload: ${type(schema)}): void`).join('; ')} }` : 'Record<string, never>';
    const slots = schema.slotIds ? 'KitSlots' : schema.slots?.length ? `{ ${schema.slots.map(name => `${JSON.stringify(name)}?: SlotNode[]`).join('; ')} }` : 'Record<string, never>';
    return `  ${component}(id: string, props${schema.props.required.length ? '' : '?'}: ${type(schema.props)}, events?: ${events}, slots?: ${slots}): KitNode<'${component}'>;`;
  }).join('\n');
  const methods = Object.entries(familyMethods).map(([component, modes]) => `  ${component}: { ${Object.entries(modes).map(([mode, methods]) => `${mode}: { ${Object.entries(methods).map(([method, schema]) => `${method}: { args: ${type(schema.args)}; result: ${type(schema.result)} }`).join('; ')} }`).join('; ')} };`).join('\n');
  const output = `// Generated by content/fixture/generate-types.mjs. Native IO is unsupported.\nimport type { KitNode, KitSlots, SlotNode } from './kit-sdk.js';\nexport interface ${name}Factories {\n${factories}\n}\nexport interface ${name}MethodContracts {\n${methods}\n}\ndeclare module './kit-sdk.js' { interface KitFactories extends ${name}Factories {} }\n`;
  const destination = new URL(`kit-${family}-sdk.d.ts`, root);
  if (process.argv.includes('--check')) {
    if (readFileSync(destination, 'utf8') !== output) throw new Error(`${family} types stale`);
  } else writeFileSync(destination, output);
}
