import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync, writeFileSync, mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { spawnSync } from 'node:child_process';
import { familySchemas, familyMethods } from '../kit-agent-schema.mjs';
import { familySchemas as gameSchemas, familyMethods as gameMethods } from '../kit-game-effects-schema.mjs';
import { validateValue, schemaType } from '../kit-schema.mjs';

function declarations(schemas, methods, name) {
  const lines = ["// Generated by tests/kit-agent.test.mjs (KIT_WRITE_TYPES=1).", "import type { KitNode, SlotNode } from './kit-sdk.js';", `export interface ${name}Factories {`];
  for (const [component, schema] of Object.entries(schemas)) {
    const events = Object.entries(schema.events).map(([event, value]) => `${JSON.stringify(event)}?(payload: ${schemaType(value)}): void`).join('; ');
    const slots = (schema.slots ?? []).map(slot => `${JSON.stringify(slot)}?: SlotNode[]`).join('; ');
    lines.push(`  ${component}(id: string, props${schema.props.oneOf || schema.props.required.length ? '' : '?'}: ${schemaType(schema.props)}, events?: { ${events} }${slots ? `, slots?: { ${slots} }` : ''}): KitNode;`);
  }
  lines.push('}', `export interface ${name}MethodContracts {`);
  for (const [component, modes] of Object.entries(methods)) {
    lines.push(`  ${component}: {`);
    for (const [mode, methods] of Object.entries(modes)) {
      lines.push(`    ${mode}: {`);
      for (const [method, schema] of Object.entries(methods)) lines.push(`      ${method}: { args: ${schemaType(schema.args)}; result: ${schemaType(schema.result)} };`);
      lines.push('    };');
    }
    lines.push('  };');
  }
  return [...lines, '}', ''].join('\n');
}

test('family declarations exactly match the closed props/events/slots/method grammar', () => {
  for (const [schemas, methods, name, file] of [[familySchemas, familyMethods, 'Agent', '../kit-agent-sdk.d.ts'], [gameSchemas, gameMethods, 'GameEffects', '../kit-game-effects-sdk.d.ts']]) {
    const expected = declarations(schemas, methods, name);
    const path = new URL(file, import.meta.url);
    if (process.env.KIT_WRITE_TYPES === '1') writeFileSync(path, expected);
    assert.equal(readFileSync(path, 'utf8'), expected);
  }
});

test('TypeScript refuses missing variant facts, native handles and wrong method results', () => {
  const directory = mkdtempSync(join(tmpdir(), 'kit-agent-types-'));
  try {
    const agent = new URL('../kit-agent-sdk.d.ts', import.meta.url).pathname;
    const game = new URL('../kit-game-effects-sdk.d.ts', import.meta.url).pathname;
    writeFileSync(join(directory, 'test.ts'), `
      import type { AgentFactories, AgentMethodContracts } from ${JSON.stringify(agent)};
      import type { GameEffectsFactories } from ${JSON.stringify(game)};
      declare const agent: AgentFactories;
      declare const game: GameEffectsFactories;
      agent.ContextGauge('g', {used:{basis:'measured',amount:23,text:'23'}});
      // @ts-expect-error no measured fact without a value
      agent.ContextGauge('g', {used:{basis:'measured'}});
      // @ts-expect-error refusal cannot carry a manufactured result
      agent.ToolCall('t', {family:'shell',tool:'build',state:{kind:'refused',reason:'Denied',output:{kind:'silent'}}});
      // @ts-expect-error no native clip handles
      game.CinematicEffect('c', {clip:123});
      // @ts-expect-error current_status is a tagged native result, not a success boolean
      const status: AgentMethodContracts['ApprovalPrompt']['query']['current_status']['result'] = true;
      // @ts-expect-error approve has named decision args
      const args: AgentMethodContracts['ApprovalPrompt']['invoke']['approve']['args'] = {always:true};
    `);
    const result = spawnSync(process.execPath, [new URL('../../app-host/node_modules/typescript/bin/tsc', import.meta.url).pathname, '--noEmit', '--strict', '--skipLibCheck', '--target', 'ES2022', '--module', 'nodenext', '--moduleResolution', 'nodenext', join(directory, 'test.ts')], { encoding: 'utf8' });
    assert.equal(result.status, 0, result.stdout + result.stderr);
  } finally { rmSync(directory, { recursive: true, force: true }); }
});

test('agent contracts reject unknown fields, service execution, unbounded data and wrong events', () => {
  const validate = (component, props) => validateValue(props, familySchemas[component].props);
  validate('ThinkingBlock', { reasoning: { kind: 'withheld', text: 'Caller refused disclosure' } });
  assert.throws(() => validate('ThinkingBlock', { reasoning: { kind: 'failed' } }));
  assert.throws(() => validate('PromptBuilder', { label: 'Fixture', state: { kind: 'ready' }, execute: true }));
  assert.throws(() => validate('ContextGauge', { used: { basis: 'measured', amount: Infinity } }));
  assert.throws(() => validateValue('approved', familySchemas.FeedbackRating.events.vote));
  assert.throws(() => validateValue({ id: 'x', name: 'n' }, familySchemas.PromptBuilder.events.slot));
  assert.throws(() => validateValue({ arbitrary: true }, familyMethods.AgentPlan.query.done.args));
  validateValue(null, familyMethods.ContextGauge.query.fraction.result);
  assert.throws(() => validateValue(1.1, familyMethods.ContextGauge.query.fraction.result));
});
