use std::env;
use std::fs;
use std::path::{Path, PathBuf};

use anyhow::{Context, Result, bail};
use gpui_kit_tokens::{Radius, Space, studio_dark, studio_dark_json};

fn main() -> Result<()> {
    let mut args = env::args().skip(1);
    match (args.next().as_deref(), args.next().as_deref()) {
        (Some("tokens"), Some("generate")) => generate(false),
        (Some("tokens"), Some("check")) => generate(true),
        _ => bail!("usage: cargo xtask tokens <generate|check>"),
    }
}

fn generate(check: bool) -> Result<()> {
    // Parsing runs the same semantic validation consumers rely on.
    let tokens = studio_dark();
    let json: serde_json::Value =
        serde_json::from_str(studio_dark_json()).context("parse bundled token JSON")?;
    let mut output = String::from(
        "<!-- @generated by `cargo xtask tokens generate`; do not edit. -->\n\
         # Studio Dark token reference\n\n\
         The JSON document is the authority. This table is a review aid.\n\n",
    );
    output.push_str("## Metadata\n\n");
    output.push_str(&format!(
        "- ID: `{}`\n- Name: `{}`\n- Appearance: `{:?}`\n\n",
        tokens.meta.id, tokens.meta.name, tokens.meta.appearance
    ));

    output.push_str("## Surfaces and text\n\n| Token | Value |\n|---|---|\n");
    for prefix in ["surface", "text", "interactive", "semantic"] {
        let object = json["color"][prefix]
            .as_object()
            .with_context(|| format!("color.{prefix} must be an object"))?;
        for (name, value) in object {
            output.push_str(&format!(
                "| `color.{prefix}.{name}` | `{}` |\n",
                value.as_str().context("color value must be a string")?
            ));
        }
    }
    for (index, value) in json["color"]["loader"]["gradient"]
        .as_array()
        .context("color.loader.gradient must be an array")?
        .iter()
        .enumerate()
    {
        output.push_str(&format!(
            "| `color.loader.gradient.{index}` | `{}` |\n",
            value.as_str().context("loader color must be a string")?
        ));
    }

    output.push_str("\n## Spacing\n\n| Step | Pixels |\n|---|---:|\n");
    for (name, step) in [
        ("xs", Space::Xs),
        ("sm", Space::Sm),
        ("md", Space::Md),
        ("lg", Space::Lg),
        ("xl", Space::Xl),
        ("xxl", Space::Xxl),
    ] {
        output.push_str(&format!("| `{name}` | {} |\n", tokens.spacing(step)));
    }

    output.push_str("\n## Radius\n\n| Step | Pixels |\n|---|---:|\n");
    for (name, step) in [
        ("small", Radius::Small),
        ("control", Radius::Control),
        ("card", Radius::Card),
        ("dialog", Radius::Dialog),
        ("bubble", Radius::Bubble),
        ("pill", Radius::Pill),
    ] {
        output.push_str(&format!("| `{name}` | {} |\n", tokens.radius(step)));
    }

    let path = root().join("docs/token-reference.md");
    if check {
        let current = fs::read_to_string(&path)
            .with_context(|| format!("read generated {}", path.display()))?;
        if current != output {
            bail!(
                "{} is stale; run `cargo xtask tokens generate`",
                path.display()
            );
        }
        println!("{} is current", path.display());
    } else {
        fs::write(&path, output).with_context(|| format!("write {}", path.display()))?;
        println!("generated {}", path.display());
    }
    Ok(())
}

fn root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .expect("xtask lives under the repository root")
        .to_path_buf()
}
