use std::env;
use std::fmt::Write as _;
use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

use anyhow::{Context, Result, bail};
use gpui_kit_tokens::{
    BorderWeight, ControlSize, Density, Elevation, Layer, MotionEasing, OpacityRole, Radius, Space,
    SpringPreset, TokenDocument, bundled, contrast,
};

fn main() -> Result<()> {
    let mut args = env::args().skip(1);
    match (args.next().as_deref(), args.next().as_deref()) {
        (Some("tokens"), Some("generate")) => tokens(false),
        (Some("tokens"), Some("check")) => tokens(true),
        (Some("scenes"), Some("list")) => scenes_list(),
        (Some("scenes"), Some("capture")) => scenes_capture(),
        _ => bail!("usage: cargo xtask <tokens generate|tokens check|scenes list|scenes capture>"),
    }
}

fn scenes_list() -> Result<()> {
    for scene in gpui_kit::scenes::catalog() {
        println!("{}", scene.name);
    }
    Ok(())
}

/// Renders every scene in every bundled theme to a reviewable image.
///
/// Each capture runs in its own process because a GPUI application owns the
/// window system for its lifetime.
fn scenes_capture() -> Result<()> {
    let directory = root().join("snapshots").join(platform()).join("scenes");
    fs::create_dir_all(&directory).with_context(|| format!("create {}", directory.display()))?;

    for theme in bundled() {
        for scene in gpui_kit::scenes::catalog() {
            let path = directory.join(format!("{}-{}.png", scene.name, theme.meta.id));
            let status = Command::new(env!("CARGO"))
                .args([
                    "run",
                    "--quiet",
                    "-p",
                    "gpui-kit-gallery",
                    "--",
                    "--scene",
                    scene.name,
                    "--theme",
                    &theme.meta.id,
                    "--capture",
                ])
                .arg(&path)
                .current_dir(root())
                .status()
                .with_context(|| format!("capture scene {}", scene.name))?;
            if !status.success() {
                bail!("capturing scene `{}` failed", scene.name);
            }
        }
    }
    println!("captured {} scenes", directory.display());
    Ok(())
}

fn platform() -> &'static str {
    if cfg!(target_os = "macos") {
        "macos"
    } else if cfg!(target_os = "windows") {
        "windows"
    } else {
        "linux"
    }
}

fn tokens(check: bool) -> Result<()> {
    contrast_gate()?;

    let mut output = String::from(
        "<!-- @generated by `cargo xtask tokens generate`; do not edit. -->\n\
         # Token reference\n\n\
         The JSON documents under `tokens/` are the authority. These tables are\n\
         a review aid, and every theme below is validated on each run.\n",
    );
    for document in bundled() {
        theme_section(&mut output, document)?;
    }

    let path = root().join("docs/token-reference.md");
    if check {
        let current = fs::read_to_string(&path)
            .with_context(|| format!("read generated {}", path.display()))?;
        if current != output {
            bail!(
                "{} is stale; run `cargo xtask tokens generate`",
                path.display()
            );
        }
        println!("{} is current", path.display());
    } else {
        fs::write(&path, output).with_context(|| format!("write {}", path.display()))?;
        println!("generated {}", path.display());
    }
    Ok(())
}

/// Fails the task rather than the document, so a contrast regression is caught
/// before it can be committed as a generated table.
fn contrast_gate() -> Result<()> {
    let mut failed = false;
    for document in bundled() {
        for failure in contrast::failures(document) {
            failed = true;
            eprintln!(
                "{}: {} on {} is {:.2}:1, below the {:.1}:1 minimum",
                document.meta.id,
                failure.foreground,
                failure.background,
                failure.ratio,
                failure.minimum
            );
        }
    }
    if failed {
        bail!("contrast requirements are not met");
    }
    Ok(())
}

/// Emits one theme, in a fixed order.
///
/// The table is built from typed accessors rather than by iterating the parsed
/// JSON, because whether `serde_json` preserves document order depends on
/// feature unification across the workspace, and a generated file must not
/// change with an unrelated dependency.
fn theme_section(output: &mut String, tokens: &TokenDocument) -> Result<()> {
    write!(
        output,
        "\n## {} (`{}`)\n\nAppearance: `{:?}`.\n",
        tokens.meta.name, tokens.meta.id, tokens.meta.appearance
    )?;

    output.push_str("\n### Palette\n\n| Token | Value |\n|---|---|\n");
    for (group, steps) in &tokens.color.palette {
        for (step, value) in steps {
            writeln!(output, "| `color.palette.{group}.{step}` | `{value}` |")?;
        }
    }

    output.push_str("\n### Semantic color\n\n| Token | Source | Resolved |\n|---|---|---|\n");
    let color = &tokens.color;
    let sources: Vec<(String, &str)> = vec![
        ("color.surface.canvas".into(), color.surface.canvas.as_str()),
        ("color.surface.panel".into(), color.surface.panel.as_str()),
        ("color.surface.raised".into(), color.surface.raised.as_str()),
        (
            "color.surface.overlay".into(),
            color.surface.overlay.as_str(),
        ),
        ("color.text.primary".into(), color.text.primary.as_str()),
        ("color.text.muted".into(), color.text.muted.as_str()),
        ("color.text.faint".into(), color.text.faint.as_str()),
        ("color.text.onAccent".into(), color.text.on_accent.as_str()),
        (
            "color.interactive.hover".into(),
            color.interactive.hover.as_str(),
        ),
        (
            "color.interactive.active".into(),
            color.interactive.active.as_str(),
        ),
        (
            "color.interactive.selected".into(),
            color.interactive.selected.as_str(),
        ),
        (
            "color.interactive.hairline".into(),
            color.interactive.hairline.as_str(),
        ),
        (
            "color.interactive.hairlineStrong".into(),
            color.interactive.hairline_strong.as_str(),
        ),
        (
            "color.interactive.focus".into(),
            color.interactive.focus.as_str(),
        ),
        (
            "color.semantic.accent".into(),
            color.semantic.accent.as_str(),
        ),
        (
            "color.semantic.accentStrong".into(),
            color.semantic.accent_strong.as_str(),
        ),
        (
            "color.semantic.danger".into(),
            color.semantic.danger.as_str(),
        ),
        (
            "color.semantic.warning".into(),
            color.semantic.warning.as_str(),
        ),
        (
            "color.semantic.success".into(),
            color.semantic.success.as_str(),
        ),
        ("color.semantic.info".into(), color.semantic.info.as_str()),
    ]
    .into_iter()
    .chain(
        color
            .loader
            .gradient
            .iter()
            .enumerate()
            .map(|(index, value)| (format!("color.loader.gradient.{index}"), value.as_str())),
    )
    .collect();

    for (path, source) in sources {
        writeln!(
            output,
            "| `{path}` | `{source}` | `{}` |",
            hex(tokens, source)
        )?;
    }

    output.push_str("\n### Spacing\n\n| Step | Pixels |\n|---|---:|\n");
    for (name, step) in [
        ("xs", Space::Xs),
        ("sm", Space::Sm),
        ("md", Space::Md),
        ("lg", Space::Lg),
        ("xl", Space::Xl),
        ("xxl", Space::Xxl),
    ] {
        writeln!(output, "| `{name}` | {} |", tokens.spacing(step))?;
    }

    output.push_str("\n### Radius\n\n| Step | Pixels |\n|---|---:|\n");
    for (name, step) in [
        ("small", Radius::Small),
        ("control", Radius::Control),
        ("card", Radius::Card),
        ("dialog", Radius::Dialog),
        ("bubble", Radius::Bubble),
        ("pill", Radius::Pill),
    ] {
        writeln!(output, "| `{name}` | {} |", tokens.radius(step))?;
    }

    output.push_str(
        "\n### Control scale\n\n| Step | Height | Padding X | Gap | Font | Icon |\n|---|---:|---:|---:|---:|---:|\n",
    );
    for (name, size) in [
        ("xs", ControlSize::Xs),
        ("sm", ControlSize::Sm),
        ("md", ControlSize::Md),
        ("lg", ControlSize::Lg),
    ] {
        let step = tokens.control(size);
        writeln!(
            output,
            "| `{name}` | {} | {} | {} | {} | {} |",
            step.height, step.padding_x, step.gap, step.font_size, step.icon_size
        )?;
    }

    output.push_str("\n### Density\n\n| Axis | Space | Control | Font |\n|---|---:|---:|---:|\n");
    for (name, density) in [
        ("compact", Density::Compact),
        ("comfortable", Density::Comfortable),
    ] {
        let scale = tokens.density(density);
        writeln!(
            output,
            "| `{name}` | {} | {} | {} |",
            scale.space, scale.control, scale.font
        )?;
    }

    output.push_str(
        "\n### Elevation\n\n| Step | Y | Blur | Spread | Color |\n|---|---:|---:|---:|---|\n",
    );
    for (name, level) in [
        ("flat", Elevation::Flat),
        ("raised", Elevation::Raised),
        ("overlay", Elevation::Overlay),
        ("modal", Elevation::Modal),
    ] {
        let step = tokens.elevation(level);
        writeln!(
            output,
            "| `{name}` | {} | {} | {} | `{}` |",
            step.y,
            step.blur,
            step.spread,
            format_color(step.color)
        )?;
    }

    output.push_str("\n### Layers\n\n| Layer | Z index |\n|---|---:|\n");
    for layer in Layer::ALL {
        writeln!(output, "| `{layer:?}` | {} |", tokens.z_index(layer))?;
    }

    output.push_str("\n### Motion\n\n| Easing | Curve |\n|---|---|\n");
    for easing in MotionEasing::ALL {
        writeln!(
            output,
            "| `{}` | `{:?}` |",
            easing.name(),
            tokens.easing(easing)
        )?;
    }
    output.push_str("\n| Spring | Stiffness | Damping | Mass |\n|---|---:|---:|---:|\n");
    for preset in SpringPreset::ALL {
        let spring = tokens.spring(preset);
        writeln!(
            output,
            "| `{}` | {} | {} | {} |",
            preset.name(),
            spring.stiffness,
            spring.damping,
            spring.mass
        )?;
    }
    output.push_str("\n| Response | Pixels |\n|---|---:|\n");
    for (name, value) in [
        ("motion.pressOffsetPx", tokens.press_offset()),
        ("motion.hoverLiftPx", tokens.hover_lift()),
    ] {
        writeln!(output, "| `{name}` | {value} |")?;
    }

    output.push_str("\n### Border and opacity\n\n| Token | Value |\n|---|---:|\n");
    for (name, value) in [
        (
            "border.hairline",
            tokens.border_width(BorderWeight::Hairline),
        ),
        ("border.thick", tokens.border_width(BorderWeight::Thick)),
        ("opacity.disabled", tokens.opacity(OpacityRole::Disabled)),
        ("opacity.muted", tokens.opacity(OpacityRole::Muted)),
        ("opacity.scrim", tokens.opacity(OpacityRole::Scrim)),
    ] {
        writeln!(output, "| `{name}` | {value} |")?;
    }

    output.push_str("\n### Effects\n\n| Token | Value |\n|---|---:|\n");
    for (name, value) in [
        ("effect.glassAlphaMacos", tokens.effect.glass_alpha_macos),
        ("effect.backdropBlur", tokens.effect.backdrop_blur),
        ("effect.edgeFadeBand", tokens.effect.edge_fade_band),
        (
            "effect.selectedRingAlpha",
            tokens.effect.selected_ring_alpha,
        ),
        ("effect.focusRingWidth", tokens.effect.focus_ring_width),
        ("effect.focusRingAlpha", tokens.effect.focus_ring_alpha),
    ] {
        writeln!(output, "| `{name}` | {value} |")?;
    }

    output.push_str(
        "\n### Contrast\n\n| Foreground | Background | Ratio | Minimum |\n|---|---|---:|---:|\n",
    );
    for check in contrast::report(tokens) {
        writeln!(
            output,
            "| `{}` | `{}` | {:.2} | {:.1} |",
            check.foreground, check.background, check.ratio, check.minimum
        )?;
    }
    Ok(())
}

fn hex(tokens: &TokenDocument, source: &str) -> String {
    let color = gpui_kit_tokens::Color::resolve("reference", source, &tokens.color.palette)
        .expect("the document is validated before it is documented");
    format_color(color)
}

fn format_color(color: gpui_kit_tokens::Color) -> String {
    let channel = |value: f32| (value * 255.0).round() as u8;
    let rgb = format!(
        "#{:02x}{:02x}{:02x}",
        channel(color.red),
        channel(color.green),
        channel(color.blue)
    );
    if color.alpha >= 1.0 {
        rgb
    } else {
        format!("{rgb}{:02x}", channel(color.alpha))
    }
}

fn root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .expect("xtask lives under the repository root")
        .to_path_buf()
}
