use std::env;
use std::fmt::Write as _;
use std::fs;
use std::path::{Path, PathBuf};

use anyhow::{Context, Result, bail};
use gpui_kit_tokens::{
    BorderWeight, ControlSize, Density, Elevation, Layer, MotionEasing, OpacityRole, Radius, Space,
    SpringPreset, TokenDocument, bundled, bundled_json, contrast,
};

fn main() -> Result<()> {
    let mut args = env::args().skip(1);
    match (args.next().as_deref(), args.next().as_deref()) {
        (Some("tokens"), Some("generate")) => tokens(false),
        (Some("tokens"), Some("check")) => tokens(true),
        _ => bail!("usage: cargo xtask tokens <generate|check>"),
    }
}

fn tokens(check: bool) -> Result<()> {
    contrast_gate()?;

    let mut output = String::from(
        "<!-- @generated by `cargo xtask tokens generate`; do not edit. -->\n\
         # Token reference\n\n\
         The JSON documents under `tokens/` are the authority. These tables are\n\
         a review aid, and every theme below is validated on each run.\n",
    );
    for (document, json) in bundled().into_iter().zip(bundled_json()) {
        let json: serde_json::Value =
            serde_json::from_str(json).context("parse bundled token JSON")?;
        theme_section(&mut output, document, &json)?;
    }

    let path = root().join("docs/token-reference.md");
    if check {
        let current = fs::read_to_string(&path)
            .with_context(|| format!("read generated {}", path.display()))?;
        if current != output {
            bail!(
                "{} is stale; run `cargo xtask tokens generate`",
                path.display()
            );
        }
        println!("{} is current", path.display());
    } else {
        fs::write(&path, output).with_context(|| format!("write {}", path.display()))?;
        println!("generated {}", path.display());
    }
    Ok(())
}

/// Fails the task rather than the document, so a contrast regression is caught
/// before it can be committed as a generated table.
fn contrast_gate() -> Result<()> {
    let mut failed = false;
    for document in bundled() {
        for failure in contrast::failures(document) {
            failed = true;
            eprintln!(
                "{}: {} on {} is {:.2}:1, below the {:.1}:1 minimum",
                document.meta.id,
                failure.foreground,
                failure.background,
                failure.ratio,
                failure.minimum
            );
        }
    }
    if failed {
        bail!("contrast requirements are not met");
    }
    Ok(())
}

fn theme_section(
    output: &mut String,
    tokens: &TokenDocument,
    json: &serde_json::Value,
) -> Result<()> {
    write!(
        output,
        "\n## {} (`{}`)\n\nAppearance: `{:?}`.\n",
        tokens.meta.name, tokens.meta.id, tokens.meta.appearance
    )?;

    output.push_str("\n### Palette\n\n| Token | Value |\n|---|---|\n");
    for (group, steps) in &tokens.color.palette {
        for (step, value) in steps {
            writeln!(output, "| `color.palette.{group}.{step}` | `{value}` |")?;
        }
    }

    output.push_str("\n### Semantic color\n\n| Token | Source | Resolved |\n|---|---|---|\n");
    for prefix in ["surface", "text", "interactive", "semantic"] {
        let object = json["color"][prefix]
            .as_object()
            .with_context(|| format!("color.{prefix} must be an object"))?;
        for (name, value) in object {
            let source = value.as_str().context("color value must be a string")?;
            writeln!(
                output,
                "| `color.{prefix}.{name}` | `{source}` | `{}` |",
                hex(tokens, source)
            )?;
        }
    }
    for (index, value) in json["color"]["loader"]["gradient"]
        .as_array()
        .context("color.loader.gradient must be an array")?
        .iter()
        .enumerate()
    {
        let source = value.as_str().context("loader color must be a string")?;
        writeln!(
            output,
            "| `color.loader.gradient.{index}` | `{source}` | `{}` |",
            hex(tokens, source)
        )?;
    }

    output.push_str("\n### Spacing\n\n| Step | Pixels |\n|---|---:|\n");
    for (name, step) in [
        ("xs", Space::Xs),
        ("sm", Space::Sm),
        ("md", Space::Md),
        ("lg", Space::Lg),
        ("xl", Space::Xl),
        ("xxl", Space::Xxl),
    ] {
        writeln!(output, "| `{name}` | {} |", tokens.spacing(step))?;
    }

    output.push_str("\n### Radius\n\n| Step | Pixels |\n|---|---:|\n");
    for (name, step) in [
        ("small", Radius::Small),
        ("control", Radius::Control),
        ("card", Radius::Card),
        ("dialog", Radius::Dialog),
        ("bubble", Radius::Bubble),
        ("pill", Radius::Pill),
    ] {
        writeln!(output, "| `{name}` | {} |", tokens.radius(step))?;
    }

    output.push_str(
        "\n### Control scale\n\n| Step | Height | Padding X | Gap | Font | Icon |\n|---|---:|---:|---:|---:|---:|\n",
    );
    for (name, size) in [
        ("xs", ControlSize::Xs),
        ("sm", ControlSize::Sm),
        ("md", ControlSize::Md),
        ("lg", ControlSize::Lg),
    ] {
        let step = tokens.control(size);
        writeln!(
            output,
            "| `{name}` | {} | {} | {} | {} | {} |",
            step.height, step.padding_x, step.gap, step.font_size, step.icon_size
        )?;
    }

    output.push_str("\n### Density\n\n| Axis | Space | Control | Font |\n|---|---:|---:|---:|\n");
    for (name, density) in [
        ("compact", Density::Compact),
        ("comfortable", Density::Comfortable),
    ] {
        let scale = tokens.density(density);
        writeln!(
            output,
            "| `{name}` | {} | {} | {} |",
            scale.space, scale.control, scale.font
        )?;
    }

    output.push_str(
        "\n### Elevation\n\n| Step | Y | Blur | Spread | Color |\n|---|---:|---:|---:|---|\n",
    );
    for (name, level) in [
        ("flat", Elevation::Flat),
        ("raised", Elevation::Raised),
        ("overlay", Elevation::Overlay),
        ("modal", Elevation::Modal),
    ] {
        let step = tokens.elevation(level);
        writeln!(
            output,
            "| `{name}` | {} | {} | {} | `{}` |",
            step.y,
            step.blur,
            step.spread,
            format_color(step.color)
        )?;
    }

    output.push_str("\n### Layers\n\n| Layer | Z index |\n|---|---:|\n");
    for layer in Layer::ALL {
        writeln!(output, "| `{layer:?}` | {} |", tokens.z_index(layer))?;
    }

    output.push_str("\n### Motion\n\n| Easing | Curve |\n|---|---|\n");
    for easing in MotionEasing::ALL {
        writeln!(
            output,
            "| `{}` | `{:?}` |",
            easing.name(),
            tokens.easing(easing)
        )?;
    }
    output.push_str("\n| Spring | Stiffness | Damping | Mass |\n|---|---:|---:|---:|\n");
    for (name, preset) in [
        ("snappy", SpringPreset::Snappy),
        ("smooth", SpringPreset::Smooth),
        ("bouncy", SpringPreset::Bouncy),
    ] {
        let spring = tokens.spring(preset);
        writeln!(
            output,
            "| `{name}` | {} | {} | {} |",
            spring.stiffness, spring.damping, spring.mass
        )?;
    }

    output.push_str("\n### Border and opacity\n\n| Token | Value |\n|---|---:|\n");
    for (name, value) in [
        (
            "border.hairline",
            tokens.border_width(BorderWeight::Hairline),
        ),
        ("border.thick", tokens.border_width(BorderWeight::Thick)),
        ("opacity.disabled", tokens.opacity(OpacityRole::Disabled)),
        ("opacity.muted", tokens.opacity(OpacityRole::Muted)),
        ("opacity.scrim", tokens.opacity(OpacityRole::Scrim)),
    ] {
        writeln!(output, "| `{name}` | {value} |")?;
    }

    output.push_str(
        "\n### Contrast\n\n| Foreground | Background | Ratio | Minimum |\n|---|---|---:|---:|\n",
    );
    for check in contrast::report(tokens) {
        writeln!(
            output,
            "| `{}` | `{}` | {:.2} | {:.1} |",
            check.foreground, check.background, check.ratio, check.minimum
        )?;
    }
    Ok(())
}

fn hex(tokens: &TokenDocument, source: &str) -> String {
    let color = gpui_kit_tokens::Color::resolve("reference", source, &tokens.color.palette)
        .expect("the document is validated before it is documented");
    format_color(color)
}

fn format_color(color: gpui_kit_tokens::Color) -> String {
    let channel = |value: f32| (value * 255.0).round() as u8;
    let rgb = format!(
        "#{:02x}{:02x}{:02x}",
        channel(color.red),
        channel(color.green),
        channel(color.blue)
    );
    if color.alpha >= 1.0 {
        rgb
    } else {
        format!("{rgb}{:02x}", channel(color.alpha))
    }
}

fn root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .expect("xtask lives under the repository root")
        .to_path_buf()
}
