[package]
name = "gpui-box-util-macros"
version = "0.1.2"
edition.workspace = true
rust-version.workspace = true
homepage.workspace = true
publish = true
license = "Apache-2.0"
description = "Utility macros for GPUI Box"

repository = "https://github.com/fran0220/gpui-box"
[lints]
workspace = true

[lib]
name = "util_macros"
path = "src/util_macros.rs"
proc-macro = true
doctest = false

[dependencies]
quote.workspace = true
syn.workspace = true

[features]
perf-enabled = []
